# Generated by Django 4.2.1 on 2023-05-22 18:46

import SolicitacoesApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolicitacoesApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producaodematerial',
            name='criar_arte',
        ),
        migrations.RemoveField(
            model_name='producaodematerial',
            name='duracao_gravacao',
        ),
        migrations.AddField(
            model_name='producaodematerial',
            name='data_agendamento',
            field=models.DateField(default='2023-01-01', verbose_name='Data de Agendamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producaodematerial',
            name='detalhes_arte',
            field=models.TextField(blank=True, validators=[SolicitacoesApp.validators.validate_min_30], verbose_name='Descreva sua arte aqui'),
        ),
        migrations.AddField(
            model_name='producaodematerial',
            name='duracao_estimada',
            field=models.CharField(default='1 hora', max_length=20, verbose_name='Duração da Estimada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producaodematerial',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
