# Generated by Django 4.2.1 on 2023-05-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolicitacoesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producaodematerial',
            name='numero_participantes',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
