# Generated by Django 4.2.1 on 2023-06-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolicitacoesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospreposto',
            name='complemento',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='viagem',
            name='complemento',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadospreposto',
            name='agencia',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='dadospreposto',
            name='banco',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='dadospreposto',
            name='conta_corrente',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='dadospreposto',
            name='endereco_bairro',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dadospreposto',
            name='endereco_logradouro',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dadospreposto',
            name='endereco_numero',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='bairro',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='cidade',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='logradouro',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='numero',
            field=models.IntegerField(max_length=6),
        ),
    ]
