# Generated by Django 4.2.1 on 2023-05-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolicitacoesApp', '0002_remove_producaodematerial_criar_arte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producaodematerial',
            name='outro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producaodematerial',
            name='data_agendamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Agendamento'),
        ),
        migrations.AlterField(
            model_name='producaodematerial',
            name='detalhes_arte',
            field=models.TextField(blank=True, null=True, verbose_name='Descreva sua arte aqui'),
        ),
        migrations.AlterField(
            model_name='producaodematerial',
            name='duracao_estimada',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Duração da Estimada'),
        ),
        migrations.AlterField(
            model_name='producaodematerial',
            name='equipe_cead',
            field=models.BooleanField(default=False, verbose_name='Precisará de nossa equipe de cinegrafistas?'),
        ),
        migrations.AlterField(
            model_name='producaodematerial',
            name='horario_agendamento',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Agendamento'),
        ),
        migrations.AlterField(
            model_name='producaodematerial',
            name='numero_participantes',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True, verbose_name='Número de participantes'),
        ),
        migrations.AlterField(
            model_name='producaodematerial',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='producaodematerial',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
