# Generated by Django 4.2.1 on 2023-06-14 13:50

import SolicitacoesApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolicitacoesApp', '0002_dadospreposto_solicitante_viagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitante',
            name='coordenador',
            field=models.CharField(max_length=100, validators=[SolicitacoesApp.validators.validate_nome_completo]),
        ),
    ]
