# Generated by Django 4.2.1 on 2023-05-26 13:56

import SolicitacoesApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolicitacoesApp', '0004_remove_producaodematerial_finalidade_gravacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producaodematerial',
            name='finalidade_solicitacao',
            field=models.TextField(default='Finalidade', validators=[SolicitacoesApp.validators.validate_min_30], verbose_name='Finalidade da Solicitação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producaodematerial',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
