# Generated by Django 4.2.1 on 2023-05-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolicitacoesApp', '0005_alter_producaodematerial_finalidade_solicitacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producaodematerial',
            name='equipe_cead',
            field=models.BooleanField(choices=[(False, 'Não, iremos utilizar a nossa própria equipe'), (True, 'Sim, precisaremos da equipe do CEAD')], default=False, verbose_name='Precisará de nossa equipe de cinegrafistas?'),
        ),
    ]
